wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.0
    framework: huggingface
    huggingface_version: 4.21.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.2
    start_time: 1661473733.571664
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 51
      - 53
      - 55
      3:
      - 13
      - 23
      4: 3.10.2
      5: 0.13.0
      6: 4.21.0
      8:
      - 5
