wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.0
    framework: huggingface
    huggingface_version: 4.21.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: conf_table._type
      5: 1
      6:
      - 1
    - 1: conf_table.sha256
      5: 1
      6:
      - 1
    - 1: conf_table.size
      5: 1
      6:
      - 1
    - 1: conf_table.artifact_path
      5: 1
      6:
      - 1
    - 1: conf_table._latest_artifact_path
      5: 1
      6:
      - 1
    - 1: conf_table.path
      5: 1
      6:
      - 1
    - 1: conf_table.ncols
      5: 1
      6:
      - 1
    - 1: conf_table.nrows
      5: 1
      6:
      - 1
    python_version: 3.10.2
    start_time: 1661473831.62322
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 51
      - 53
      - 55
      2:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 51
      - 53
      - 55
      3:
      - 7
      - 13
      - 23
      4: 3.10.2
      5: 0.13.0
      6: 4.21.0
      8:
      - 4
      - 5
    visualize:
      conf:
        panel_config:
          fieldSettings:
            Actual: Actual
            Predicted: Predicted
            nPredictions: nPredictions
          panelDefId: wandb/confusion_matrix/v1
          stringSettings:
            title: ''
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: conf_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
lr:
  desc: null
  value: 0.01
model_name:
  desc: null
  value: google/bert_uncased_L-2_H-128_A-2
